import Ember from 'ember';

export default Ember.Route.extend({

  model: function () {
    return [
      {
        id: "1",
        name: "Integrated with Hackster.io",
        description: "As part of the integration of Hackster.io with SparkFun's ecommerce platform, I built a data-sharing integration to add and update products from both sides.  Now SparkFun parts on Hackster.io are accurately linked to SparkFun product pages.  Also for a given SparkFun product, we query Hackster.io's database for projects using that product and display the most popular project on SparkFun's product page.  As part of this integration, users can also create a Hackster.io project from a SparkFun wishlist.",
        url: "https://www.sparkfun.com/products/12060",
        github: "",
        skills: ["PHP", "PostgreSQL", "Created script to import ids to existing products", "Hackster.io API", "jQuery"],
        image: "/assets/screen_shot_hackster.png",
        medium: "",
        climate: "",
        climateBadge: "",
        travisCI: "",
        travisCIbadge: "",
      },

      {
        id: "2",
        name: "Pebble Hackathon - Exploreians",
        description: "During the Pebble Time Hackathon, I helped create a game for a Pebble Time watch where you can interact and collect different companions depending on your terrian called Exploreians.  This app did not use your phone for GPS and instead used a prototype GPS SmartStrap with an Arduino Pro Mini and Flora GPS module.  I initially used Pebble.js to build the game, but needed to switch over to C two-thirds into the hackathon so we could have color images and get the prototype SmartStrap to communicate to the game.  This game is similiar to Pokemon Go! but we created this a few days before Pokemon Go! was announced.",
        url: "https://www.hackster.io/team-transplants/exploreians",
        github: "https://github.com/figmentbml/pebblehack",
        skills: ["WatchApp", "Pebble.js", "Hackathon"],
        image: "/assets/pebblehack.png",
        medium: "",
        climate: "",
        climateBadge: "",
        travisCI: "",
        travisCIbadge: "",
      },
/*
      {
        id: "3",
        name: "CSC160: Homework",
        description: "Things",
        url: "",
        github: "",
        skills: ["C++"],
        image: "",
        medium: "",
        climate: "",
        climateBadge: "",
        travisCI: "",
        travisCIbadge: "",
      },
*/
      {
        id: "4",
        name: "Colorado Wine Tracker",
        description: "A Rails app that provides information about Colorado Wineries and their wine. It keeps track of your tasting notes so you can remember if you liked that wine and explore how a wine changes over time.",
        url: "http://www.wine-tracker.co/",
        github: "https://github.com/figmentbml/wine-tracker",
        skills: ["Ruby on Rails", "Gems: Yelp API, Carrierwave, Fog, Nokogiri", "PostgreSQL", "Rake Tasks", "Scraping Sites", "Forms", "User Authorization", "Bootstrap", "Associations", "Controller Specs"],
        image: "/assets/Screen Shot wine tracker.png",
        medium: "http://medium.com/gschool-chronicles/introducing-colorado-wine-tracker-a2006ad18171",
        climate: "https://codeclimate.com/github/figmentbml/wine-tracker",
        climateBadge: "https://codeclimate.com/github/figmentbml/wine-tracker/badges/gpa.svg",
        travisCI: "https://travis-ci.org/figmentbml/wine-tracker",
        travisCIbadge: "https://travis-ci.org/figmentbml/wine-tracker.svg?branch=master",
      },
      {
        id: "5",
        name: "Rantly",
        description: "An app with Ember.js and a Rails API, which was built from a list of stories for functionality and a mock site for design.  It requires users to make rants that are at least 144 characters long and has client/server user auth.",
        url: "",
        github: "https://github.com/figmentbml/rantly-ember",
        skills: ["Ember.js", "Client/Server User Auth", "Rails API", "Client/Server Validations", "Gravatar API", "Inline Editing", "Search Rants", "Associations", "PostgreSQL"],
        image: "/assets/Screen Shot rantly.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/ember-rantly",
        climateBadge: "https://codeclimate.com/github/figmentbml/rantly-ember/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },
      {
        id: "6",
        name: "gCamp",
        description: "A Rails app we built for class that is similar to Basecamp. It was our first full Rails app and helped us learn about development processes.",
        url: "http://stormy-cove-1200.herokuapp.com/",
        github: "https://github.com/figmentbml/gCamp",
        skills: ["Ruby on Rails", "Join Tables", "User Authorization", "Bootstrap", "Associations", "Rspec", "Capybara", "PostgreSQL"],
        image: "/assets/Screen Shot gcamp.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/gCamp",
        climateBadge: "https://codeclimate.com/github/figmentbml/gCamp/badges/gpa.svg",
        travisCI: "https://travis-ci.org/figmentbml/gCamp",
        travisCIbadge: "https://travis-ci.org/figmentbml/gCamp.svg?branch=master",
      },
      {
        id: "7",
        name: "This Portfolio",
        description: "First Ember app containing more information about me, information about my projects, and my resume. It was also my first web app using Handlebars.js.",
        url: "http://beth-jaswa.herokuapp.com/",
        github: "https://github.com/figmentbml/portfolio",
        skills: ["Ember.js", "Handlebars.js", "all custom CSS & HTML"],
        image: "/assets/Screen Shot portfolio.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/portfolio",
        climateBadge: "https://codeclimate.com/github/figmentbml/portfolio/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },
      {
        id: "8",
        name: "Ember Blog",
        description: "Basic blog with Ember front end powered by a Rails API. Features include posts, comments, and users.",
        url: "http://jaswa-blog.herokuapp.com/",
        github: "https://github.com/figmentbml/blog-client",
        skills: ["Ember.js", "Handlebars.js", "Rails API", "Ember Associations", "Collection Select", "Search Posts", "Flash Messages", "all custom CSS & HTML"],
        image: "/assets/Screen Shot blog.png",
        medium: "https://medium.com/gschool-chronicles/search-bar-madness-27f98e1d0654",
        climate: "https://codeclimate.com/github/figmentbml/blog-client",
        climateBadge: "https://codeclimate.com/github/figmentbml/blog-client/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },

      {
        id: "9",
        name: "Rails Blog API",
        description: "Rails API for a blog with posts, comments, and users returning different JSON depending on if it's hit from Ember or Angular.",
        url: "",
        github: "https://github.com/figmentbml/beth-blog-api",
        skills: ["Building an API", "Search Posts", "PostgreSQL"],
        image: "/assets/Screen Shot rails api.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/beth-blog-api",
        climateBadge: "https://codeclimate.com/github/figmentbml/beth-blog-api/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },

      ];
  }

});
