import Ember from 'ember';

export default Ember.Route.extend({

  model: function () {
    return [
      {
        id: "1",
        name: "Integrated with Hackster.io",
        description: "This project led me to add Hackster's part id to SparkFun's database for certain products.  Now popular projects made with a SparkFun part are highlighted on those product pages.  I also added functionality to our internal system to allow Catalog to push new products and update old ones to Hackster.io directly. Hackster.io users will not need to add those products themselves and can focus on inputing their projects.  This also allowed SparkFun to have more accurate information and product url on Hackster.io's website.",
        url: "https://www.sparkfun.com/products/12060",
        github: "",
        skills: ["PHP", "PostgreSQL", "Created script to import ids to existing products", "API"],
        image: "/assets/screen_shot_hackster.png",
        medium: "",
        climate: "",
        climateBadge: "",
        travisCI: "",
        travisCIbadge: "",
      },

      {
        id: "2",
        name: "Pebble Hackathon - Exploreians",
        description: "Exploreians is a game for your Pebble Time watch where you can interact and collect different companions depending on your terrian.  This app did not use your phone for GPS and instead used a prototype GPS SmartStrap with an Arduino Pro Mini and Flora GPS module.  We actually created 2 apps: one using Pebble.js and one in C.  This game is similiar to Pokemon Go! but we created this a few days before Pokemon Go! came out.",
        url: "https://www.hackster.io/team-transplants/exploreians",
        github: "https://github.com/figmentbml/pebbleHackTake2",
        skills: ["WatchApp", "Pebble.js", "Hackathon"],
        image: "/assets/pebblehack.png",
        medium: "",
        climate: "",
        climateBadge: "",
        travisCI: "",
        travisCIbadge: "",
      },
/*
      {
        id: "3",
        name: "CSC160: Homework",
        description: "Things",
        url: "",
        github: "",
        skills: ["C++"],
        image: "",
        medium: "",
        climate: "",
        climateBadge: "",
        travisCI: "",
        travisCIbadge: "",
      },
*/
      {
        id: "4",
        name: "Colorado Wine Tracker",
        description: "A Rails app that provides information about Colorado Wineries and their wine. It keeps track of your tasting notes so you can remember if you liked that wine and explore how a wine changes over time.",
        url: "http://www.wine-tracker.co/",
        github: "https://github.com/figmentbml/wine-tracker",
        skills: ["Ruby on Rails", "Gems: Yelp API, Carrierwave, Fog, Nokogiri", "PostgreSQL", "Rake Tasks", "Scraping Sites", "Forms", "User Authorization", "Bootstrap", "Associations", "Controller Specs"],
        image: "/assets/Screen Shot wine tracker.png",
        medium: "http://medium.com/gschool-chronicles/introducing-colorado-wine-tracker-a2006ad18171",
        climate: "https://codeclimate.com/github/figmentbml/wine-tracker",
        climateBadge: "https://codeclimate.com/github/figmentbml/wine-tracker/badges/gpa.svg",
        travisCI: "https://travis-ci.org/figmentbml/wine-tracker",
        travisCIbadge: "https://travis-ci.org/figmentbml/wine-tracker.svg?branch=master",
      },
      {
        id: "5",
        name: "Rantly",
        description: "An app with Ember.js and a Rails API, which was built from a list of stories for functionality and a mock site for design.  It requires users to make rants that are at least 144 characters long and has client/server user auth.",
        url: "http://jaswa-rantly.herokuapp.com/",
        github: "https://github.com/figmentbml/rantly-ember",
        skills: ["Ember.js", "Client/Server User Auth", "Rails API", "Client/Server Validations", "Gravatar API", "Inline Editing", "Search Rants", "Associations", "PostgreSQL"],
        image: "/assets/Screen Shot rantly.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/ember-rantly",
        climateBadge: "https://codeclimate.com/github/figmentbml/rantly-ember/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },
      {
        id: "6",
        name: "gCamp",
        description: "A Rails app we built for class that is similar to Basecamp. It was our first full Rails app and helped us learn about development processes.",
        url: "http://stormy-cove-1200.herokuapp.com/",
        github: "https://github.com/figmentbml/gCamp",
        skills: ["Ruby on Rails", "Join Tables", "User Authorization", "Bootstrap", "Associations", "Rspec", "Capybara", "PostgreSQL"],
        image: "/assets/Screen Shot gcamp.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/gCamp",
        climateBadge: "https://codeclimate.com/github/figmentbml/gCamp/badges/gpa.svg",
        travisCI: "https://travis-ci.org/figmentbml/gCamp",
        travisCIbadge: "https://travis-ci.org/figmentbml/gCamp.svg?branch=master",
      },
      {
        id: "7",
        name: "This Portfolio",
        description: "First Ember app containing more information about me, information about my projects, and my resume. It was also my first web app using Handlebars.js.",
        url: "http://beth-jaswa.herokuapp.com/",
        github: "https://github.com/figmentbml/portfolio",
        skills: ["Ember.js", "Handlebars.js", "all custom CSS & HTML"],
        image: "/assets/Screen Shot portfolio.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/portfolio",
        climateBadge: "https://codeclimate.com/github/figmentbml/portfolio/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },
      {
        id: "8",
        name: "Ember Blog",
        description: "Basic blog with Ember front end powered by a Rails API. Features include posts, comments, and users.",
        url: "http://jaswa-blog.herokuapp.com/",
        github: "https://github.com/figmentbml/blog-client",
        skills: ["Ember.js", "Handlebars.js", "Rails API", "Ember Associations", "Collection Select", "Search Posts", "Flash Messages", "all custom CSS & HTML"],
        image: "/assets/Screen Shot blog.png",
        medium: "https://medium.com/gschool-chronicles/search-bar-madness-27f98e1d0654",
        climate: "https://codeclimate.com/github/figmentbml/blog-client",
        climateBadge: "https://codeclimate.com/github/figmentbml/blog-client/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },

      {
        id: "9",
        name: "Rails Blog API",
        description: "Rails API for a blog with posts, comments, and users returning different JSON depending on if it's hit from Ember or Angular.",
        url: "",
        github: "https://github.com/figmentbml/beth-blog-api",
        skills: ["Building an API", "Search Posts", "PostgreSQL"],
        image: "/assets/Screen Shot rails api.png",
        medium: "",
        climate: "https://codeclimate.com/github/figmentbml/beth-blog-api",
        climateBadge: "https://codeclimate.com/github/figmentbml/beth-blog-api/badges/gpa.svg",
        travisCI: "",
        travisCIbadge: "",
      },

      ];
  }

});
